[project]
name = "debugging-q4"
version = "0.1.0"
description = "CCHC Assessment Debugging Q4"
authors = [{ name = "Andrew Rowan", email = "arowan19993@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.0.4",
    "pandas>=2.2.3",
    "numpy>=2.3.0",
]
